apiVersion: kro.run/v1alpha1
kind: ResourceGraphDefinition
metadata:
  name: mondamail
spec:
  schema:
    apiVersion: v1alpha1
    kind: Mondamail
    spec:
      deployment:
        replicas: integer
        image: string
      configuration:
        subnets: "[]map[string]string"
        hostname: "[]string"
  resources:
    - id: deployment
      template:
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          replicas: ${schema.spec.deployment.replicas}
          selector:
            matchLabels:
              app: ${schema.metadata.name}
          template:
            metadata:
              labels:
                app: ${schema.metadata.name}
            spec:
              containers:
                - name: ${schema.metadata.name}
                  image: ${schema.spec.deployment.image}
                  ports:
                    - containerPort: 80
    - id: service
      template:
        apiVersion: v1
        kind: Service
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          type: ClusterIP
          selector:
            app: ${schema.metadata.name}
          ports:
            - protocol: TCP
              port: 80
              targetPort: 80
    - id: targetgroup
      template:
        apiVersion: gateway.k8s.aws/v1beta1
        kind: TargetGroupConfiguration
        metadata:
          name: ${schema.metadata.name}
          namespace: ${schema.metadata.namespace}
        spec:
          routeConfigurations:
            - routeIdentifier:
                kind: HTTPRoute
                name: ${schema.metadata.name}-http
                namespace: ${schema.metadata.namespace}
              targetGroupProps:
                healthCheckConfig:
                  healthCheckPath: /
                  healthCheckProtocol: HTTP
          targetReference:
            name: ${schema.metadata.name}
          defaultConfiguration:
            targetType: ip
    - id: httproute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.metadata.name}-http
          namespace: ${schema.metadata.namespace}
        spec:
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: alb
            namespace: default
            sectionName: http
          hostnames: ${schema.spec.configuration.hostname}
          rules:
            - filters:
              - type: RequestRedirect
                requestRedirect:
                  scheme: https
                  statusCode: 301
    - id: httpsroute
      template:
        apiVersion: gateway.networking.k8s.io/v1
        kind: HTTPRoute
        metadata:
          name: ${schema.metadata.name}-https
          namespace: ${schema.metadata.namespace}
        spec:
          parentRefs:
          - group: gateway.networking.k8s.io
            kind: Gateway
            name: alb
            namespace: default
            sectionName: https
          hostnames: ${schema.spec.configuration.hostname}
          rules:
            - backendRefs:
              - name: ${schema.metadata.name}
                port: 80
              matches:
                - path:
                    type: PathPrefix
                    value: /
